### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Techbrunch** [jeroenvisser101/LeakyBucket#5]
Hello,

I'm planning to use this library to implement rate limiting in our API but there is some changes that I would like to make.

If I look at the code example:

``` php
// Fill the bucket
$bucket->fill();

// Check if it's full
if ($bucket->isFull()) {
...
}
```

`fill()` is "touching" the bucket and then `isFull()` calls `leak` which also touches the bucket. Which mean the the bucket will actually never leak because the time between those 2 statements will be almost 0.

Changes I'm suggesting:
- [ ] `touch()` should only be called when saving the bucket.
- [ ] `isFull()` should only check if the bucket is full and not call `leak()` and `overflow`
- [ ] `overflow()` should also not be part of the `fill()` function and the user should be in charge of calling it manually. It could be useful to let the bucket overflow in certain situations. One possiblity is also to add a setting to let the user chose if if does not want the bucket to overflow and maybe also add another setting with a max_overflow.

I have to leave now but I would love to hear your thoughts. By the way are you using this code in production ?

**Comment by jeroenvisser101** [comment]
It sounds cool! I was using this code in production, but then the site died (not due to this haha). I am using this package in [ninjaphp/ninja](https://github.com/ninjaphp/ninja). I'll have another look at this tonight, although I don't think I'll have the time to implement them on short notice. I could add you as a contributor though? As long as we stick to semver we can make sure we don't break production code :)

**Comment by Techbrunch** [comment]
Two others improvements:
- [ ] The constructor should initialize the bucket property if it cannot be retrieved from storage
- [ ] Should'n reset only reset the number of drops and the timestamp instead of deleting the key ?
